version: '3'
services:
  mongodb:
    image: mongo
    networks:
      - production-network

  webnode:
    build:
      dockerfile: ./docker/image-search.dockerfile
      context: .
    image: node
    container_name: imagesearch
    networks:
      - production-network
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb"

networks:
  production-network:
    driver: bridge
